registrationform/basicapp/urls.py
from django.urls import path, include
from . import views

app_name = 'basicapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
]

registrationform/userauth/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('', include('basicapp.urls')),
    path('admin/', admin.site.urls),
]

registrationform/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

registrationform/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

registrationform/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm
# Create your views here.


def index(request):
    return render(request, 'basicapp/index.htm')



def register(request):
    

    registered = False


    if request.method == "POST": 
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basicapp/registration.htm', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

registrationform/templates/basicapp/base.htm
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <title>Base</title>
</head>

<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'basicapp:index' %}" class="navbar-brand">DJANGO</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">ADMIN</a></li>
                <li><a href="{% url 'basicapp:register' %}" class="navbar-link">REGISTER</a></li>

            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}
        {% endblock %}
    </div>



</body>

</html>

registrationform/templates/basicapp/index.htm
{% extends "basicapp/base.htm" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Registration</h1>

</div>

{% endblock %}

registrationform/templates/basicapp/registration.htm
{% extends "basicapp/base.htm" %}
{% load staticfiles %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>

        {% endif %}

    </div>

</div>

{% endblock %}